### ISSUE TITLE
Transfer back to Homebridge Plugin Group? 

### ISSUE THREAD

**Issue by donavanbecker** [devbobo/homebridge-arlo#150]
@EpicKris, since you haven’t really worked on this plugin, do you want to transfer this back to the homebridge-plugin Organization?

**Comment by SmolSoftBoi** [comment]
After attempting to transfer ownership I get an error: `Cannot find new owner 'homebridge-plugin'`?

**Comment by donavanbecker** [comment]
Transfer to me and I can transfer

**Comment by donavanbecker** [comment]
@EpicKris Can you just transfer it to me?

**Comment by donavanbecker** [comment]
@EpicKris so you are going too?

**Comment by SmolSoftBoi** [comment]
Yes, already done.
