### ISSUE TITLE
Mode switch stopped working after tvOS 15.0 / HomePod Version 15.0 Update

### ISSUE THREAD

**Issue by mpatfield** [devbobo/homebridge-arlo#163]
**Describe Your Problem:**
When switching between Away and any other mode in the Home app, it gets stuck in "Arming/Disarming..." state indefinitely. The only recent changes I made was to update my AppleTV and HomePod to the latest version. Has anybody else been having issues since the latest update?

**Logs:**
Nothing shows in the Homebridge logs when I try to switch between modes. Happy to provide more detailed logs if somebody can talk me through it.

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX,
        "pin": "XXX-XX-XXX"
    },
    "accessories": [
    ],
    "platforms": [
            ]
        },
        {
            "name": "Arlo",
            "email": "xxx@yyy.com",
            "password": "********",
            "include_cameras": false,
            "platform": "Arlo"
        }
    ]
}
```

**Screenshots:**
![IMG_7B3EA5F5E39E-1](https://user-images.githubusercontent.com/18125347/134730830-c521c00d-c7b2-4a51-a239-4afd2e8fa2f5.jpeg)

**Environment:**

* **Node.js Version**: 12.16.2
* **NPM Version**: 2.1.0
* **Homebridge Version**: 1.3.4
* **Homebridge GSH Plugin Version**: N/A
* **Homebridge Config UI X Plugin Version**: 4.41.2
* **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by matharris7** [comment]
I noticed this too but it seems to be a HomeKit issue.  The system does arm/disarm.  Just need to close Home app and reopen
